### ISSUE TITLE
Add ability to blend "private" and public "results"

### ISSUE THREAD

**Issue by teolemon** [algolia/algoliasearch-django-example#1]
Use case: being able to search in a private model, filtered by owner and a public model, unfiltered.

Possible solutions:
- search using Algolia, filter Django and blend both (performance drawback)
- search using Algolia, and have Magic™ happen (privacy drawback)

**Comment by tkrugg** [comment]
Closing this for housekeeping as it's too old. If you're still experiencing the same issue and would like to see it addressed, please do reopen it.
